### ISSUE TITLE
Mark as Server-Side on Modrinth

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [KosmX/minecraftPlayerAnimator#84]
**Is your feature request related to a problem? Please describe.**
I use a [tool](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/modrinth-modpacks/) to automatically download modpacks from Modrinth and start a server with them. The way it works is that it downloads any mods marked as server-side and tries to start the server. Unfortunately, my [current modpack](https://modrinth.com/modpack/hypnos-wither-storm-pack) uses [Better Combat](https://modrinth.com/mod/better-combat), a mod with a server-side component that depends on playerAnimator to work. Since this mod isn't marked as a server mod, it's not downloaded by default and the server will fail to run.

**Describe the solution you'd like**
I'd like the mod on Modrinth to be marked as server-side so that it will download when a server-side mod depends on it.

**Describe alternatives you've considered**
Manually adding the mod works fine, but it'd be a lot more convenient to have the pack be automatically configured without extra tweaking.

**Comment by creeloper27** [comment]
To add to this I am using these 2 other mods that also require this mod as a dependency on the server side: [Spell Engine](https://modrinth.com/mod/spell-engine), [Fastload](https://modrinth.com/mod/fastload) (+ [Better Combat](https://modrinth.com/mod/better-combat) as well also in my case).

Example server output in my particular setup:
```
> /usr/lib/jvm/java-17-openjdk-amd64/bin/java -Xms1G -Xmx12G -jar fabric-server*.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[05:11:03] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.7
[05:11:03] [ForkJoinPool-1-worker-14/WARN]: Mod mr_vanilla_refresh uses the version 1.4.19c which isn't compatible with Loader's extended semantic version format (Could not parse version number component '19c'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:11:03] [ForkJoinPool-1-worker-1/WARN]: Mod explorify uses the version v1.3.0-mc1.20 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:11:03] [ForkJoinPool-1-worker-10/WARN]: Mod creategoggles uses the version 0.5.5.f which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'f'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:11:03] [ForkJoinPool-1-worker-7/WARN]: Mod io_netty_netty-handler-proxy uses the version 4.1.82.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:11:03] [ForkJoinPool-1-worker-12/WARN]: Mod journeymap uses the version 5.9.18p1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '18p1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:11:03] [ForkJoinPool-1-worker-12/WARN]: Mod org_cache2k_cache2k-api uses the version 2.6.1.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:11:03] [ForkJoinPool-1-worker-12/WARN]: Mod org_cache2k_cache2k-core uses the version 2.6.1.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:11:03] [ForkJoinPool-1-worker-7/WARN]: Mod io_netty_netty-codec-http uses the version 4.1.82.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:11:03] [ForkJoinPool-1-worker-7/WARN]: Mod io_netty_netty-codec-socks uses the version 4.1.82.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[05:11:03] [main/WARN]: Mod resolution failed
[05:11:03] [main/INFO]: Immediate reason: [HARD_DEP archers 1.0.7+1.20.1 {depends spell_engine @ [>=0.12.3+1.20.1]}, HARD_DEP_NO_CANDIDATE spell_engine 0.12.5+1.20.1 {depends player-animator @ [>=0.9.9]}, ROOT_FORCELOAD_SINGLE archers 1.0.7+1.20.1]
[05:11:03] [main/INFO]: Reason: [HARD_DEP spell_engine 0.12.5+1.20.1 {depends player-animator @ [>=0.9.9]}, HARD_DEP bettercombat 1.8.4+1.20.1 {depends player-animator @ [>=1.0.0]}, HARD_DEP fastload_fapi_forward 1.0.2 {depends minecraft @ [1.19.1]}]
[05:11:03] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, modmenu, sodium-extra, enhanced_attack_indicator, fabric-screen-api-v1, fabric-renderer-indigo, reeses-sodium-options, exordium, bobby, charmonium, flywheel, fabric-sound-api-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1, spruceui, fabric-model-loading-api-v1, lambdynlights, iris, immediatelyfast, indium, fabric-client-tags-api-v1, fabric-blockrenderlayer-v1, dynamic_fps, sodium, fabric-renderer-registries-v1, fabric-models-v0, advancementplaques]
[05:11:03] [main/INFO]: Fix: add [add:player-animator 1.0.0 ([[1.0.0,∞)])], remove [], replace []
[05:11:03] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
         - Install player-animator, version 1.0.0 or later.
More details:
         - Mod 'Spell Engine' (spell_engine) 0.12.5+1.20.1 requires version 0.9.9 or later of player-animator, which is missing!
         - Mod 'Better Combat' (bettercombat) 1.8.4+1.20.1 requires version 1.0.0 or later of player-animator, which is missing!
         - Mod 'Fastload Fabric-api Forwarding' (fastload_fapi_forward) 1.0.2 requires version 1.19.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.7-launcher.1.0.0.jar:1.0.0]
```

**Comment by 0xSnowflakeXD** [comment]
Fastload doesn't actually need `player-animator` because it play with Minecraft world mechanics to load the world faster. What Fastload needs is 1.20.1 version of Minecraft, so you can upgrade your server or find a version of Fastload compatible with 1.19.1.
@creeloper27

**Comment by creeloper27** [comment]
> Fastload doesn't actually need `player-animator` because it play with Minecraft world mechanics to load the world faster. What Fastload needs is 1.20.1 version of Minecraft, so you can upgrade your server or find a version of Fastload compatible with 1.19.1. @creeloper27

My server is already running minecraft `1.20.1`, the log I attached to my first comment clearly states that `[05:11:03] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.7`.
I have no idea why that is happening, usually tho it goes away once I add all the other dependencies required.
The original problem still stands that both [Spell Engine](https://modrinth.com/mod/spell-engine) and [Better Combat](https://modrinth.com/mod/better-combat) require this mod to also be server side.

**Comment by 0xSnowflakeXD** [comment]
> > Fastload doesn't actually need `player-animator` because it play with Minecraft world mechanics to load the world faster. What Fastload needs is 1.20.1 version of Minecraft, so you can upgrade your server or find a version of Fastload compatible with 1.19.1. @creeloper27
> 
> My server is already running minecraft `1.20.1`, the log I attached to my first comment clearly states that `[05:11:03] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.7`. I have no idea why that is happening, usually tho it goes away once I add all the other dependencies required. The original problem still stands that both [Spell Engine](https://modrinth.com/mod/spell-engine) and [Better Combat](https://modrinth.com/mod/better-combat) require this mod to also be server side.

Sorry, i mean 1.19.1 version of Fastload running on 1.20.1
It might never work...

**Comment by creeloper27** [comment]
> > > Fastload doesn't actually need `player-animator` because it play with Minecraft world mechanics to load the world faster. What Fastload needs is 1.20.1 version of Minecraft, so you can upgrade your server or find a version of Fastload compatible with 1.19.1. @creeloper27
> > 
> > 
> > My server is already running minecraft `1.20.1`, the log I attached to my first comment clearly states that `[05:11:03] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.7`. I have no idea why that is happening, usually tho it goes away once I add all the other dependencies required. The original problem still stands that both [Spell Engine](https://modrinth.com/mod/spell-engine) and [Better Combat](https://modrinth.com/mod/better-combat) require this mod to also be server side.
> 
> Sorry, i mean 1.19.1 version of Fastload running on 1.20.1 It might never work...

Oh yeah that is weird, I don't notice that, tho it seems to work fine on a `1.20.1` server, I use `packwiz` to maintain this modpack and it choose this version so I guess it's fine, the mod file name is actually `Fastload+1.18.2-1.20-3.4.0.jar` (it does not seem to include 1.20.1), tho on the [Modrinth download page](https://modrinth.com/mod/fastload/version/3.4.0) it sais `Game versions
1.18.2–1.20.1` so that is weird, the dev probably forgot to include `1.20.1` in the mod file name and in the mod configs as I do not get this version error anymore if I add `player-animator`, it seems the [dev of that mod is not maintaining it anymore](https://github.com/BumbleSoftware/Fastload/issues/103) tho that is irrelevant for this Issue as this mod is still needed server side by the other 2 mods [Spell Engine](https://modrinth.com/mod/spell-engine) and [Better Combat](https://modrinth.com/mod/better-combat).
